### ISSUE TITLE
Need a preview

### ISSUE THREAD

**Issue by tebenia** [azamuddin/polished-template#1]
Hello, can you please provide a preview, so that anyone can see it first before download it azamuddin?
Thank you.

**Comment by imdbsd** [comment]
Hi, i think you can see the preview through this repo github page here: https://azamuddin.github.io/polished-template/

He include the link in facebook post, CMIIW.

**Comment by azamuddin** [comment]
Yes, @imdbsd is correct. You can check the link.

**Comment by tebenia** [comment]
Good, now I want to have a parallax please..
