### ISSUE TITLE
Remove container-fluid from homepage

### ISSUE THREAD

**Issue by qya** [azamuddin/polished-template#3]
Hello im really like about copycat metro ui + bootstrap
I recommended to change container-fluid into container only
coz its look horrible if u using container fluid
Thanks

**Comment by azamuddin** [comment]
Hi qya, this template has nothing to do with metro ui. It's based on Polaris instead. 
This is just template, you can customize they way you want for example removing container fluid. 

Could you elaborate what you meant by horrible?

**Comment by qya** [comment]
Yep this is just my suggestion 💃
