### ISSUE TITLE
Findings Lost CSS For DataTables

### ISSUE THREAD

**Issue by wicaksonoe** [azamuddin/polished-template#4]
Just information, on demo table page. The DataTable section is not completely working because the CSS for DataTables doesn't embedded. If you want to use DataTables on your project, you can simply add DataTables javaScript and CSS on your project file.

CMIIW
Cheers :beers:

**Comment by azamuddin** [comment]
Thank you. The CSS for datatables actually handled by polished.min.css 

But yes you're right, to use with datatables the script of datatables (javascript) file need to be inserted. 

Information has been added to the documentation. 

Thanks a lot.
